import { useEffect, useState } from "react";
import { intelligence } from "../api/client";
import { cn } from "../lib/utils";
import { PreviewBanner } from "../components/PreviewBanner";

function Badge({ variant, children }: { variant: "green" | "red" | "yellow" | "blue" | "neutral"; children: React.ReactNode }) {
  const colors = {
    green: "bg-green-500/15 text-green-500",
    red: "bg-red-500/15 text-red-500",
    yellow: "bg-yellow-500/15 text-yellow-500",
    blue: "bg-primary/15 text-primary",
    neutral: "bg-muted text-muted-foreground",
  };
  return <span className={cn("inline-block px-2 py-0.5 rounded text-xs font-semibold uppercase tracking-wider", colors[variant])}>{children}</span>;
}

export function TradeView() {
  const [strategies, setStrategies] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    intelligence.strategies().then(setStrategies).finally(() => setLoading(false));
  }, []);

  const handleApprove = async (id: string) => {
    await intelligence.updateStrategyStatus(id, "approved");
    setStrategies((prev) => prev.map((s) => (s.id === id ? { ...s, status: "approved" } : s)));
  };

  const handleCancel = async (id: string) => {
    await intelligence.updateStrategyStatus(id, "cancelled");
    setStrategies((prev) => prev.map((s) => (s.id === id ? { ...s, status: "cancelled" } : s)));
  };

  if (loading) return <div className="flex items-center justify-center p-10 text-muted-foreground">Loading strategies...</div>;

  const proposed = strategies.filter((s) => s.status === "proposed");
  const active = strategies.filter((s) => ["approved", "partial", "executed"].includes(s.status));
  const closed = strategies.filter((s) => ["closed", "cancelled"].includes(s.status));

  return (
    <div className="p-6 max-w-6xl mx-auto">
      <PreviewBanner
        title="Trade"
        description="Review and approve strategy proposals generated by Dexter. Trade execution requires a connected brokerage via SnapTrade."
        requirement="Ask Dexter to propose a trade in Chat — strategies will appear here for approval."
      />
      <div className="mb-6">
        <h2 className="text-2xl font-semibold tracking-tight">Trade</h2>
        <p className="text-sm text-muted-foreground mt-1">Strategy proposals, execution, and order history</p>
      </div>

      {strategies.length === 0 ? (
        <div className="text-center py-16 text-muted-foreground">
          <h3 className="text-foreground font-semibold mb-2">No strategies yet</h3>
          <p className="text-sm">Ask Dexter to analyze a stock and propose a trade. Strategies will appear here for review.</p>
        </div>
      ) : (
        <>
          {proposed.length > 0 && (
            <div className="mb-6">
              <h3 className="text-lg font-semibold mb-3">Pending Approval ({proposed.length})</h3>
              {proposed.map((s) => (
                <div key={s.id} className="rounded-xl border border-border bg-card p-5 mb-4">
                  <div className="flex items-center justify-between mb-4">
                    <h4 className="font-semibold">{s.name}</h4>
                    <div className="flex gap-2">
                      <Badge variant={s.executionMode === "auto" ? "green" : "yellow"}>{s.executionMode}</Badge>
                      <Badge variant={s.direction === "long" ? "green" : s.direction === "short" ? "red" : "neutral"}>{s.direction}</Badge>
                    </div>
                  </div>

                  {s.legs?.length > 0 && (
                    <div className="overflow-x-auto mb-4">
                      <table className="w-full text-sm">
                        <thead>
                          <tr className="border-b border-border">
                            {["Symbol", "Side", "Qty", "Entry", "Target", "Stop"].map((h) => (
                              <th key={h} className="text-left py-2 px-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground">{h}</th>
                            ))}
                          </tr>
                        </thead>
                        <tbody>
                          {s.legs.map((leg: any, i: number) => (
                            <tr key={i} className="border-b border-border/50">
                              <td className="py-2.5 px-3 font-semibold">{leg.symbol}</td>
                              <td className="py-2.5 px-3"><Badge variant={leg.side === "buy" ? "green" : "red"}>{leg.side}</Badge></td>
                              <td className="py-2.5 px-3 tabular-nums">{leg.quantity}</td>
                              <td className="py-2.5 px-3 tabular-nums">${leg.entryPrice?.toFixed(2) ?? "-"}</td>
                              <td className="py-2.5 px-3 tabular-nums text-green-500">${leg.targetPrice?.toFixed(2) ?? "-"}</td>
                              <td className="py-2.5 px-3 tabular-nums text-red-500">${leg.stopPrice?.toFixed(2) ?? "-"}</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  )}

                  {s.risk && (
                    <div className="grid grid-cols-4 gap-4 mb-4">
                      <div className="text-center">
                        <div className="text-lg font-bold text-red-500">${s.risk.maxLoss?.toFixed(0)}</div>
                        <div className="text-xs text-muted-foreground uppercase tracking-wider mt-0.5">Max Loss</div>
                      </div>
                      <div className="text-center">
                        <div className="text-lg font-bold text-green-500">${s.risk.targetGain?.toFixed(0)}</div>
                        <div className="text-xs text-muted-foreground uppercase tracking-wider mt-0.5">Target Gain</div>
                      </div>
                      <div className="text-center">
                        <div className="text-lg font-bold">{s.risk.rewardRiskRatio?.toFixed(1)}:1</div>
                        <div className="text-xs text-muted-foreground uppercase tracking-wider mt-0.5">R:R</div>
                      </div>
                      <div className="text-center">
                        <div className="text-lg font-bold">{s.risk.positionSizePercent?.toFixed(1)}%</div>
                        <div className="text-xs text-muted-foreground uppercase tracking-wider mt-0.5">Position Size</div>
                      </div>
                    </div>
                  )}

                  <div className="flex gap-2">
                    <button onClick={() => handleApprove(s.id)} className="px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/80 transition-colors">Approve</button>
                    <button onClick={() => handleCancel(s.id)} className="px-4 py-2 rounded-lg border border-border text-red-500 text-sm font-medium hover:bg-red-500/10 transition-colors">Reject</button>
                  </div>
                </div>
              ))}
            </div>
          )}

          {active.length > 0 && (
            <div className="mb-6">
              <h3 className="text-lg font-semibold mb-3">Active ({active.length})</h3>
              {active.map((s) => (
                <div key={s.id} className="rounded-xl border border-border bg-card p-5 mb-4 flex items-center justify-between">
                  <span className="font-semibold">{s.name}</span>
                  <Badge variant="green">{s.status}</Badge>
                </div>
              ))}
            </div>
          )}

          {closed.length > 0 && (
            <div>
              <h3 className="text-lg font-semibold mb-3">History ({closed.length})</h3>
              {closed.map((s) => (
                <div key={s.id} className="rounded-xl border border-border bg-card p-5 mb-4 opacity-60 flex items-center justify-between">
                  <span className="font-semibold">{s.name}</span>
                  <Badge variant="neutral">{s.status}</Badge>
                </div>
              ))}
            </div>
          )}
        </>
      )}
    </div>
  );
}
